root: true
env:
  es6: true
  node: true
globals:
  DEBUG: readonly
  WASMC_VERSION: readonly
extends:
  - eslint:recommended
  - plugin:import/recommended
  - eslint-config-prettier
parserOptions:
  ecmaVersion: latest
  parser: babel-eslint
  sourceType: module
  createDefaultProgram: true
rules:
  new-cap: off
  no-invalid-this: off
  no-unused-vars: warn
  require-jsdoc: off
  valid-jsdoc: off
  import/no-named-as-default: off
settings:
  import/resolver:
    - node
    - alias:
        map:
          - ['@', './src']
          - ['~', './node_modules']
        extensions:
          - .js
